resources:
  - filename: ./res/example_resource.txt
    description: This is an example resource file.
  - filename: ./res/another_resource.txt
    name: alternate_name.md
    description: This is an example resource file.

